import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import { cn } from "@/lib/utils";
import NavBar from "@/components/ui/NavBar";

export const metadata: Metadata = {
  title: "Dashboard - ArtStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-slate-50 antialiased")}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
