import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import {
  Table,
  TableBody,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import NavBar from "@/components/ui/NavBar";
import { getOrdersWithStatusAll } from "@/lib/prisma";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Orders - ArtStore",
  description: "Generated by create next app",
};

export default async function Orders() {
  return (
    <>
      <NavBar />
      <div className="flex min-h-screen w-full flex-col">
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
          <Breadcrumb className="hidden md:flex">
            <BreadcrumbList>
              <BreadcrumbItem>
                <BreadcrumbLink asChild>
                  <Link className="text-base text-slate-500" href="/dashboard">
                    Dashboard
                  </Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbLink asChild>
                  <Link
                    className="text-base text-slate-800"
                    href="/dashboard/orders"
                  >
                    Stock
                  </Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
          <div className="max-w-3xl">
            <Card x-chunk="dashboard-06-chunk-0">
              <CardHeader>
                <CardTitle className="text-2xl">Frame Stock</CardTitle>
                <CardDescription>
                  Manage your stock and view their details.
                </CardDescription>
              </CardHeader>

              <CardContent>
                <Table className="">
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-[100px]">Frame Size</TableHead>
                      <TableHead>Needed Stock</TableHead>
                      <TableHead>Rate</TableHead>
                      <TableHead className="text-right">Amount</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-medium"> 6 x 9</TableCell>
                      <TableCell>17</TableCell>
                      <TableCell>720</TableCell>
                      <TableCell className="text-right">5950</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium"> 8 x 12</TableCell>
                      <TableCell>17</TableCell>
                      <TableCell>870</TableCell>
                      <TableCell className="text-right">5950</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium"> 12 x 18</TableCell>
                      <TableCell>17</TableCell>
                      <TableCell>350</TableCell>
                      <TableCell className="text-right">5950</TableCell>
                    </TableRow>
                  </TableBody>
                  <TableFooter>
                    <TableRow>
                      <TableCell colSpan={3}>Total</TableCell>
                      <TableCell className="text-right">$2,500.00</TableCell>
                    </TableRow>
                  </TableFooter>
                </Table>
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
    </>
  );
}
